### ISSUE TITLE
時間操作の神と寝てる暇などないという実績が、自分だけ時間が変わるせいかもしれませんが、解除できません。

### ISSUE THREAD

**Issue by kinoko2k** [jaoafa/jao-Super-Achievement2#36]
### 不具合の説明

```markdown
自環境だけかもしれませんが、
「時間操作の神」と「寝てる暇などない」という実績が、自分だけ時間が変わるせいかもしれませんが、解除できません。
「寝てる暇などない」=>夜にしても寝れません。
```

### 再現手順

```markdown
1. 権限グループ「`Verified`」のプレイヤー「`Kinoko_2K`」がコマンド「`/time set (時間)`」を実行する
2. 実績が解除できない。
```

### スクリーンショット

```markdown
エラーないです。
```

**Comment by yuuahp** [comment]
`/minecraft:time set <time>` を実行すると、全体の時間を夜にできます。

**Comment by yuuahp** [comment]
`/time` は自動的に `/mymaid4:time` と認識されるので、自分から見た時間しか変化しません。

**Comment by kinoko2k** [comment]
![image](https://user-images.githubusercontent.com/65443692/161406191-0238801c-547d-4646-a4d5-85c7b75d504e.png)
`/minecraf:time set day`を実行しましたが無理でした。

**Comment by book000** [comment]
v2.5.19で修正されました。
MyMaid4で実装された「timeによる時間操作を実行者のみに適用する」機能によって発生した不具合です。関連: https://github.com/jaoafa/MyMaid4/issues/280 https://github.com/jaoafa/MyMaid4/pull/285

以下の対応をしました:

- No.16 時間操作の神: 従来はバニラtimeコマンドのパーミッションノードを所有しているかを確認していましたが、`mymaid.time` に変更しました。
- No.24 寝てる暇などない: 従来は「キャンセルされずにきちんと寝たか」を確認していましたがキャンセルされた場合でも解除できるようになりました（昼間でもベッドにインタラクトすれば解除できます）
