### ISSUE TITLE
表記ミス？

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/jao-Super-Achievement2#5]
`]`が消えているようです
![jsa2](https://user-images.githubusercontent.com/75877469/115013269-c6846280-9eeb-11eb-9d03-ef5f2e8eb96f.PNG)

**Comment by book000** [comment]
:kanashimi:

**Comment by book000** [comment]
アップデートが正常に行われていなかったようです。とりあえずコンソールから見る限り解決したように見えるのでクローズします。
